export const GET_ALL_EVENTS_REQ = "GET_ALL_EVENTS_REQ"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAIL = "GET_ALL_EVENTS_FAIL"

export const CREATE_EVENT_REQ = "CREATE_EVENT_REQ"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL"

export const GET_ALL_EXHIBITION_REQ = "GET_ALL_EXHIBITION_REQ"
export const GET_ALL_EXHIBITION_SUCCESS = "GET_ALL_EXHIBITION_SUCCESS"
export const GET_ALL_EXHIBITION_FAIL = "GET_ALL_EXHIBITION_FAIL"

export const APPROVE_EVENTS_REQ = "APPROVE_EVENTS_REQ"
export const APPROVE_EVENTS_SUCCESS = "APPROVE_EVENTS_SUCCESS"
export const APPROVE_EVENTS_FAIL = "APPROVE_EVENTS_FAIL"

export const GET_ALL_USERS_REQ = "GET_ALL_USERS_REQ"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"

