export const GET_ALL_BOOKING_REQ = "GET_ALL_BOOKING_REQ"
export const GET_ALL_BOOKING_SUCCESS = "GET_ALL_BOOKING_SUCCESS"
export const GET_ALL_BOOKING_FAIL = "GET_ALL_BOOKING_FAIL"

export const CHANGE_BOOKSTATUS_REQ = "CHANGE_BOOKSTATUS_REQ"
export const CHANGE_BOOKSTATUS_SUCCESS = "CHANGE_BOOKSTATUS_SUCCESS"
export const CHANGE_BOOKSTATUS_FAIL = "CHANGE_BOOKINGSTATUS_FAIL"

export const TIMESLOTSBYROOMNAMEANDDATE_REQ = "TIMESLOTSBYROOMNAMEANDDATE_REQ"
export const TIMESLOTSBYROOMNAMEANDDATE_SUCCESS = "TIMESLOTSBYROOMNAMEANDDATE_SUCCESS"
export const TIMESLOTSBYROOMNAMEANDDATE_FAIL = "TIMESLOTSBYROOMNAMEANDDATE_FAIL"