export const ADMIN_SIGNUP_REQ = "ADMIN_SIGNUP_REQ"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_SIGNIN_REQ = "ADMIN_SIGNIN_REQ"
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL"

export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const ADMIN_RESETEMAIL_REQ = "ADMIN_RESETEMAIL_REQ"
export const ADMIN_RESETEMAIL_SUCCESS = "ADMIN_RESETEMAIL_SUCCESS"
export const ADMIN_RESETEMAIL_FAIL = "ADMIN_RESETEMAIL_FAIL"

export const ADMIN_VERIFYOTP_REQ = "ADMIN_VERIFYOTP_REQ"
export const ADMIN_VERIFYOTP_SUCCESS = "ADMIN_VERIFYOTP_SUCCESS"
export const ADMIN_VERIFYOTP_FAIL = "ADMIN_VERIFYOTP_FAIL"

export const ADMIN_RESETPASSWORD_REQ = "ADMIN_RESETPASSWORD_REQ"
export const ADMIN_RESETPASSWORD_SUCCESS = "ADMIN_RESETPASSWORD_SUCCESS"
export const ADMIN_RESETPASSWORD_FAIL = "ADMIN_RESETPASSWORD_FAIL"

export const APPROVE_USER_REQ = "APPROVE_USER_REQ"
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS"
export const APPROVE_USER_FAIL = "APPROVE_USER_FAIL"
