export const CHECKPREMIUM_REQ = "CHECKPREMIUM_REQ"
export const CHECKPREMIUM_SUCCESS = "CHECKPREMIUM_SUCCESS"
export const CHECKPREMIUM_FAIL = "CHECKPREMIUM_FAIL"

export const TIMESLOTSBY_ROOMNAME_REQ = "TIMESLOTSBY_ROOMNAME_REQ"
export const TIMESLOTSBY_ROOMNAME_SUCCESS = "TIMESLOTSBY_ROOMNAME_SUCCESS"
export const TIMESLOTSBY_ROOMNAME_FAIL = "TIMESLOTSBY_ROOMNAME_FAIL"

export const CREATE_BOOK_REQ = "CREATE_BOOK_REQ"
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS"
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL"
export const CREATE_BOOK_RESET = "CREATE_BOOK_RESET"