export const GET_ALL_EVENTS_REQ = "GET_ALL_EVENTS_REQ"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAIL = "GET_ALL_EVENTS_FAIL"

export const USER_BOOKLIST_EMAIL_REQ = "USER_BOOKLIST_EMAIL_REQ"
export const USER_BOOKLIST_EMAIL_SUCCESS = "USER_BOOKLIST_EMAIL_SUCCESS"
export const USER_BOOKLIST_EMAIL_FAIL = "USER_BOOKLIST_EMAIL_FAIL"

export const CREATE_EVENTREQUEST_REQ = "CREATE_EVENTREQUEST_REQ"
export const CREATE_EVENTREQUEST_SUCCESS = "CREATE_EVENTREQUEST_SUCCESS"
export const CREATE_EVENTREQUEST_FAIL = "CREATE_EVENTREQUEST_FAIL"