export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"

export const USER_RESETEMAIL_REQ = "USER_RESETEMAIL_REQ"
export const USER_RESETEMAIL_SUCCESS = "USER_RESETEMAIL_SUCCESS"
export const USER_RESETEMAIL_FAIL = "USER_RESETEMAIL_FAIL"

export const USER_VERIFYOTP_REQ = "USER_VERIFYOTP_REQ"
export const USER_VERIFYOTP_SUCCESS = "USER_VERIFYOTP_SUCCESS"
export const USER_VERIFYOTP_FAIL = "USER_VERIFYOTP_FAIL"

export const USER_RESETPASSWORD_REQ = "USER_RESETPASSWORD_REQ"
export const USER_RESETPASSWORD_SUCCESS = "USER_RESETPASSWORD_SUCCESS"
export const USER_RESETPASSWORD_FAIL = "USER_RESETPASSWORD_FAIL"
